export default function TermsPage() {
  return (
    <main className="flex min-h-screen flex-col items-center bg-slate-950 text-slate-50">
      <section className="w-full max-w-3xl px-4 lg:px-0 py-10">
        <h1 className="text-2xl md:text-3xl font-semibold mb-4">Terms of Use & Disclaimer</h1>
        <p className="text-xs text-slate-500 mb-8">Last updated: February 7, 2026</p>

        <div className="space-y-6 text-sm text-slate-200">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. Nature of the Service</h2>
            <p>
              SmartRelocate is an information and planning tool that uses structured data and AI models to help users
              understand immigration options and prepare their relocation dossiers. It is <strong>not</strong> a law
              firm, immigration agency, or legal representative.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. No Legal or Professional Advice</h2>
            <p>
              The content provided by SmartRelocate (including chat replies, eligibility reports, checklists and draft
              documents) is for <strong>information and planning purposes only</strong>. It does not constitute legal,
              tax, or professional advice. For complex or borderline cases, you should consult a qualified lawyer or
              immigration professional in the relevant jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. User Responsibility</h2>
            <p>
              You are solely responsible for: (a) the accuracy, completeness and truthfulness of the information you
              provide; (b) reviewing and correcting all draft documents generated by SmartRelocate; and (c) the final
              submission of your application to the relevant authorities.
            </p>
            <p className="mt-2">
              SmartRelocate does not submit applications on your behalf and does not interact directly with immigration
              authorities in your name.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. AI-Generated Content and Limitations</h2>
            <p>
              SmartRelocate uses AI models to generate summaries, explanations and draft texts based on public or
              semi-public information about immigration rules and the data you provide about your situation. While we
              make reasonable efforts to keep our data up to date and to reduce AI hallucinations, information may be
              incomplete, outdated or inaccurate. Authorities may interpret or apply rules differently, and final
              decisions always remain at their discretion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. No Guarantee of Approval</h2>
            <p>
              Using SmartRelocate does not guarantee that your visa, permit or application will be approved. Many
              factors are outside our control, including changes in laws, regulations or policies, the discretion of
              case officers, and any additional documents or checks requested by authorities.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, SmartRelocate and its owners, directors, employees and
              contractors shall not be liable for any loss, damage or cost resulting from decisions you make based on
              the information or documents generated by the service, nor for any rejection, delay or change to your
              immigration status by any authority.
            </p>
            <p className="mt-2">
              In any case, SmartRelocate&apos;s total liability for any claim related to the service is limited to the total
              amount you paid to use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Changes to the Service and Terms</h2>
            <p>
              We may update the service, the underlying data and these terms from time to time. When material changes
              are made, we will update the &quot;last updated&quot; date above and, where appropriate, notify users via the
              website or email.
            </p>
          </section>
        </div>

        <hr className="my-10 border-slate-800" />

        <h2 className="text-xl font-semibold mb-2">Conditions d&apos;utilisation &amp; Avertissement (FR)</h2>
        <p className="text-xs text-slate-500 mb-6">Résumé en français – la version anglaise prévaut en cas de conflit.</p>

        <div className="space-y-6 text-sm text-slate-200">
          <section>
            <h3 className="font-semibold mb-1">1. Nature du service</h3>
            <p>
              SmartRelocate est un outil d&apos;information et de planification qui utilise des données structurées et des
              modèles d&apos;IA pour aider les utilisateurs à comprendre leurs options d&apos;immigration et à préparer leur
              dossier de relocalisation. Ce n&apos;est ni un cabinet d&apos;avocats, ni une agence d&apos;immigration, ni un
              représentant légal.
            </p>
          </section>

          <section>
            <h3 className="font-semibold mb-1">2. Absence de conseil juridique ou professionnel</h3>
            <p>
              Le contenu fourni par SmartRelocate a une vocation d&apos;information et de planification uniquement. Il ne
              constitue pas un conseil juridique, fiscal ou professionnel. Pour les situations complexes, vous devez
              consulter un professionnel qualifié.
            </p>
          </section>

          <section>
            <h3 className="font-semibold mb-1">3. Responsabilité de l&apos;utilisateur</h3>
            <p>
              Vous êtes seul responsable des informations que vous fournissez, de la relecture et de la correction des
              documents générés, et de la soumission finale de votre dossier aux autorités compétentes.
            </p>
          </section>

          <section>
            <h3 className="font-semibold mb-1">4. Contenu généré par IA et limites</h3>
            <p>
              Malgré nos efforts pour maintenir nos données à jour, les informations peuvent être incomplètes ou
              obsolètes et les autorités peuvent appliquer les règles différemment. Les décisions finales restent à
              leur seule discrétion.
            </p>
          </section>

          <section>
            <h3 className="font-semibold mb-1">5. Aucune garantie d&apos;acceptation</h3>
            <p>
              L&apos;utilisation de SmartRelocate ne garantit en aucun cas que votre visa, permis ou demande sera accepté.
            </p>
          </section>

          <section>
            <h3 className="font-semibold mb-1">6. Limitation de responsabilité</h3>
            <p>
              La responsabilité totale de SmartRelocate au titre de toute réclamation liée au service est limitée au
              montant total que vous avez payé pour utiliser le service.
            </p>
          </section>
        </div>
      </section>
    </main>
  );
}
