export default function DisclaimerPage() {
  return (
    <main className="flex min-h-screen flex-col items-center bg-slate-950 text-slate-50">
      <section className="w-full max-w-3xl px-4 lg:px-0 py-10">
        <h1 className="text-2xl md:text-3xl font-semibold mb-4">Disclaimer</h1>
        <p className="text-xs text-slate-500 mb-8">Last updated: February 7, 2026</p>

        <div className="space-y-4 text-sm text-slate-200">
          <p>
            SmartRelocate is an AI-assisted planning tool. The information and documents generated by the service are
            drafts for your own review and use. They are provided for information and planning purposes only and do not
            constitute legal, tax, or professional advice.
          </p>
          <p>
            You are responsible for checking all details and for the final submission of your application to the
            relevant authorities. SmartRelocate does not file applications on your behalf and does not act as a legal
            representative.
          </p>
          <p>
            Using SmartRelocate does not guarantee that your visa, permit or application will be approved. Final
            decisions always remain at the discretion of the competent authorities.
          </p>
        </div>

        <hr className="my-10 border-slate-800" />

        <h2 className="text-xl font-semibold mb-2">Avertissement (FR)</h2>
        <p className="text-xs text-slate-500 mb-6">Résumé en français – la version anglaise prévaut en cas de conflit.</p>

        <div className="space-y-4 text-sm text-slate-200">
          <p>
            SmartRelocate est un outil de planification assistée par IA. Les informations et documents générés sont des
            brouillons à relire et utiliser par vous-même. Ils ont une vocation d&apos;information et de planification
            uniquement et ne constituent pas un conseil juridique, fiscal ou professionnel.
          </p>
          <p>
            Vous êtes responsable de la vérification de tous les détails et de la soumission finale de votre dossier
            aux autorités compétentes. SmartRelocate ne dépose pas de demandes en votre nom et n&apos;agit pas comme
            représentant légal.
          </p>
          <p>
            L&apos;utilisation de SmartRelocate ne garantit en aucun cas que votre visa, permis ou demande sera accepté.
            Les décisions finales restent toujours à la seule discrétion des autorités compétentes.
          </p>
        </div>
      </section>
    </main>
  );
}
